### ISSUE TITLE
NOHEATCLOUD error

### ISSUE THREAD

**Issue by Beherith** [ashdnazg/bos2cob#1]
Does not like noheatcloud
See Unitscript.cpp:766
Result below, bad script attached.

Traceback (most recent call last):
  File "bos2cob.py", line 1154, in <module>
    main(sys.argv[1])
  File "bos2cob.py", line 1112, in main
    comp = Compiler(root)
  File "bos2cob.py", line 445, in **init**
    self.parse(tree)
  File "bos2cob.py", line 455, in parse
    self.parse_children(node)
  File "bos2cob.py", line 461, in parse_children
    self.parse(child)
  File "bos2cob.py", line 453, in parse
    self._compile_funcs[node_type](node)
  File "bos2cob.py", line 468, in parse_file
    self.parse_children(node)
  File "bos2cob.py", line 461, in parse_children
    self.parse(child)
  File "bos2cob.py", line 455, in parse
    self.parse_children(node)
  File "bos2cob.py", line 461, in parse_children
    self.parse(child)
  File "bos2cob.py", line 453, in parse
    self._compile_funcs[node_type](node)
  File "bos2cob.py", line 491, in parse_funcDec
    self.parse(node[4])
  File "bos2cob.py", line 455, in parse
    self.parse_children(node)
  File "bos2cob.py", line 461, in parse_children
    self.parse(child)
  File "bos2cob.py", line 455, in parse
    self.parse_children(node)
  File "bos2cob.py", line 461, in parse_children
    self.parse(child)
  File "bos2cob.py", line 453, in parse
    self._compile_funcs[node_type](node)
  File "bos2cob.py", line 589, in parse_keywordStatement
    self.parse(child_node)
  File "bos2cob.py", line 453, in parse
    self._compile_funcs[node_type](node)
  File "bos2cob.py", line 678, in parse_expression
    self.parse(op_term[1])
  File "bos2cob.py", line 453, in parse
    self._compile_funcs[node_type](node)
  File "bos2cob.py", line 701, in parse_term
    self._code += self.get_variable(node[0].get_text(), True)
  File "bos2cob.py", line 755, in get_variable
    raise Exception("Var not found: %s" % (var_name,))
Exception: Var not found: NOHEATCLOUD
[chicken1.zip](https://github.com/ashdnazg/bos2cob/files/147093/chicken1.zip)

**Comment by Beherith** [comment]
oh wow, it was just missing from my exptype.h!

**Comment by ashdnazg** [comment]
I know, I've tested this on BAR scripts ^^
(+ BA, TechA, ZK, some S44 and XTA)
